# Generated by Django 2.0 on 2019-03-15 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=64)),
                ('nickname', models.CharField(max_length=30, null=True)),
                ('head', models.CharField(max_length=100, null=True)),
                ('sex', models.CharField(max_length=2, null=True)),
                ('register_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
