# Generated by Django 2.0 on 2019-03-17 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0002_auto_20190315_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='register_time',
        ),
    ]
