# Generated by Django 2.0 on 2019-03-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0003_remove_userinfo_register_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='uid',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
