# Generated by Django 2.0 on 2019-03-21 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0004_auto_20190321_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uid',
            field=models.CharField(max_length=64),
        ),
    ]
