# Generated by Django 2.0 on 2019-03-22 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0005_auto_20190321_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='head',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='sex',
        ),
    ]
