# Generated by Django 2.0 on 2019-03-22 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0006_auto_20190322_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='nickname',
        ),
    ]
