# Generated by Django 2.0 on 2019-03-19 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190319_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='updated',
        ),
    ]
